### Register Test
POST {{baseUrl}}/{{baseApiUri}}/register
Content-Type: application/json

{
  "username": "cuihe500",
  "email": "1337985150@qq.com",
  "password": "Ch870219176!",
  "name": "崔昌赫",
  "age": 24
}

### Login Test
POST {{baseUrl}}/{{baseApiUri}}/login
Content-Type: application/json

{
  "username": "cuihe500",
  "email": "",
  "password": "Ch870219176!"
}

### Get All User Info Test
GET {{baseUrl}}/{{baseApiUri}}/users

### Get User Info By Id Test
GET {{baseUrl}}/{{baseApiUri}}/user/get/id/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImUwOGMzYWE0LTRhMmUtNDAxMi05MjU5LTFhNjk3NWRlMjdiOSIsImlzcyI6ImtvYnJhIiwic3ViIjoidXNlcnMiLCJhdWQiOlsiY3VpaGU1MDAiXSwiZXhwIjoxNzEyODQ5MTY1LCJuYmYiOjE3MTI4MzgzNjUsImlhdCI6MTcxMjgzODM2NX0.2_fndFP1P_ypM3iUlyu6l_UEODs3N59zAd9ZK46_BQk

### What I Want To Say
GET {{baseUrl}}/{{baseApiUri}}/what-i-want-to-say
