[global]
mode = "development"

[server]
host = "0.0.0.0"
port = 8000

[database]
host = "192.168.125.112"
port = 43307
username = "root"
password = "Ch870219176!"
database_name = "users"

[loglevel]
default = "info"
database = "info"

[redis]
host = "192.168.125.112"
port = 46379
password = ""
db = 0

[rbac]
host = "192.168.125.112"
port = 43307
username = "root"
password = "Ch870219176!"
database_name = "casbin"
rbac_model_filepath = "config/rbac_model.conf"